// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.0-devel
// 	protoc        v3.12.4
// source: hostagent.proto

package landscape_hostagent_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstanceState reports the supported states of an instance communicated by the agent.
type InstanceState int32

const (
	InstanceState_Stopped InstanceState = 0
	InstanceState_Running InstanceState = 1
)

// Enum value maps for InstanceState.
var (
	InstanceState_name = map[int32]string{
		0: "Stopped",
		1: "Running",
	}
	InstanceState_value = map[string]int32{
		"Stopped": 0,
		"Running": 1,
	}
)

func (x InstanceState) Enum() *InstanceState {
	p := new(InstanceState)
	*p = x
	return p
}

func (x InstanceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceState) Descriptor() protoreflect.EnumDescriptor {
	return file_hostagent_proto_enumTypes[0].Descriptor()
}

func (InstanceState) Type() protoreflect.EnumType {
	return &file_hostagent_proto_enumTypes[0]
}

func (x InstanceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceState.Descriptor instead.
func (InstanceState) EnumDescriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{0}
}

// CommandState reports the current state of a command sent from Landscape
type CommandState int32

const (
	CommandState_Queued     CommandState = 0
	CommandState_InProgress CommandState = 1
	CommandState_Completed  CommandState = 2
)

// Enum value maps for CommandState.
var (
	CommandState_name = map[int32]string{
		0: "Queued",
		1: "InProgress",
		2: "Completed",
	}
	CommandState_value = map[string]int32{
		"Queued":     0,
		"InProgress": 1,
		"Completed":  2,
	}
)

func (x CommandState) Enum() *CommandState {
	p := new(CommandState)
	*p = x
	return p
}

func (x CommandState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandState) Descriptor() protoreflect.EnumDescriptor {
	return file_hostagent_proto_enumTypes[1].Descriptor()
}

func (CommandState) Type() protoreflect.EnumType {
	return &file_hostagent_proto_enumTypes[1]
}

func (x CommandState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandState.Descriptor instead.
func (CommandState) EnumDescriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_hostagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{0}
}

type HostAgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token             string                        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                                          // token corresponds to the Pro token subscription. Discared on on-prem landscape server.
	Uid               string                        `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`                                                              // uid is empty on the first request if the host never contacted landscape. Landscape generates one for the hostagent to send it back with each transaction.
	Hostname          string                        `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                    // hostname is literally the name of the host itself.
	Instances         []*HostAgentInfo_InstanceInfo `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances,omitempty"`                                                  // instances are all the machine instances registered on the machine.
	AccountName       string                        `protobuf:"bytes,5,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`                           // account_name is the account used in Landscape SaaS.
	RegistrationKey   *string                       `protobuf:"bytes,6,opt,name=registration_key,json=registrationKey,proto3,oneof" json:"registration_key,omitempty"`         // registration_key is an optional account-wide key used to register clients.
	DefaultInstanceId *string                       `protobuf:"bytes,7,opt,name=default_instance_id,json=defaultInstanceId,proto3,oneof" json:"default_instance_id,omitempty"` // default_instance_id is the id of the default instance.
}

func (x *HostAgentInfo) Reset() {
	*x = HostAgentInfo{}
	mi := &file_hostagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAgentInfo) ProtoMessage() {}

func (x *HostAgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAgentInfo.ProtoReflect.Descriptor instead.
func (*HostAgentInfo) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{1}
}

func (x *HostAgentInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HostAgentInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *HostAgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostAgentInfo) GetInstances() []*HostAgentInfo_InstanceInfo {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *HostAgentInfo) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *HostAgentInfo) GetRegistrationKey() string {
	if x != nil && x.RegistrationKey != nil {
		return *x.RegistrationKey
	}
	return ""
}

func (x *HostAgentInfo) GetDefaultInstanceId() string {
	if x != nil && x.DefaultInstanceId != nil {
		return *x.DefaultInstanceId
	}
	return ""
}

// Command is an instruction that landscape can send via its stream to the host agent.
// The command is self-explanatory or specified.
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// only one command can be passed at a time.
	//
	// Types that are assignable to Cmd:
	//
	//	*Command_AssignHost_
	//	*Command_Start_
	//	*Command_Stop_
	//	*Command_Install_
	//	*Command_Uninstall_
	//	*Command_SetDefault_
	//	*Command_ShutdownHost_
	Cmd isCommand_Cmd `protobuf_oneof:"cmd"`
	// request_id is a  unique identifier assigned by landscape to each command request.
	RequestId string `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_hostagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{2}
}

func (m *Command) GetCmd() isCommand_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (x *Command) GetAssignHost() *Command_AssignHost {
	if x, ok := x.GetCmd().(*Command_AssignHost_); ok {
		return x.AssignHost
	}
	return nil
}

func (x *Command) GetStart() *Command_Start {
	if x, ok := x.GetCmd().(*Command_Start_); ok {
		return x.Start
	}
	return nil
}

func (x *Command) GetStop() *Command_Stop {
	if x, ok := x.GetCmd().(*Command_Stop_); ok {
		return x.Stop
	}
	return nil
}

func (x *Command) GetInstall() *Command_Install {
	if x, ok := x.GetCmd().(*Command_Install_); ok {
		return x.Install
	}
	return nil
}

func (x *Command) GetUninstall() *Command_Uninstall {
	if x, ok := x.GetCmd().(*Command_Uninstall_); ok {
		return x.Uninstall
	}
	return nil
}

func (x *Command) GetSetDefault() *Command_SetDefault {
	if x, ok := x.GetCmd().(*Command_SetDefault_); ok {
		return x.SetDefault
	}
	return nil
}

func (x *Command) GetShutdownHost() *Command_ShutdownHost {
	if x, ok := x.GetCmd().(*Command_ShutdownHost_); ok {
		return x.ShutdownHost
	}
	return nil
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_AssignHost_ struct {
	AssignHost *Command_AssignHost `protobuf:"bytes,1,opt,name=assign_host,json=assignHost,proto3,oneof"`
}

type Command_Start_ struct {
	Start *Command_Start `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type Command_Stop_ struct {
	Stop *Command_Stop `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

type Command_Install_ struct {
	Install *Command_Install `protobuf:"bytes,4,opt,name=install,proto3,oneof"`
}

type Command_Uninstall_ struct {
	Uninstall *Command_Uninstall `protobuf:"bytes,5,opt,name=uninstall,proto3,oneof"`
}

type Command_SetDefault_ struct {
	SetDefault *Command_SetDefault `protobuf:"bytes,6,opt,name=set_default,json=setDefault,proto3,oneof"`
}

type Command_ShutdownHost_ struct {
	ShutdownHost *Command_ShutdownHost `protobuf:"bytes,7,opt,name=shutdown_host,json=shutdownHost,proto3,oneof"`
}

func (*Command_AssignHost_) isCommand_Cmd() {}

func (*Command_Start_) isCommand_Cmd() {}

func (*Command_Stop_) isCommand_Cmd() {}

func (*Command_Install_) isCommand_Cmd() {}

func (*Command_Uninstall_) isCommand_Cmd() {}

func (*Command_SetDefault_) isCommand_Cmd() {}

func (*Command_ShutdownHost_) isCommand_Cmd() {}

// CommandStatus is a message sent by the host agent reporting the current status of a Command.
type CommandStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// request_id is the unique identifier of the command request this message is about.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// command_state is the current state of handling for the spcific command being reported.
	CommandState CommandState `protobuf:"varint,2,opt,name=command_state,json=commandState,proto3,enum=landscapehostagentapi.CommandState" json:"command_state,omitempty"`
	// error is the reason of failure to complete such command or empty on the success case.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CommandStatus) Reset() {
	*x = CommandStatus{}
	mi := &file_hostagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStatus) ProtoMessage() {}

func (x *CommandStatus) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStatus.ProtoReflect.Descriptor instead.
func (*CommandStatus) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{3}
}

func (x *CommandStatus) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandStatus) GetCommandState() CommandState {
	if x != nil {
		return x.CommandState
	}
	return CommandState_Queued
}

func (x *CommandStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// InstanceInfo gather all the information of a given instance.
type HostAgentInfo_InstanceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                  // name is the hostname of the instance.
	VersionId     string        `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`                                                       // version_id string as in VERSION_ID in /etc/os-release
	InstanceState InstanceState `protobuf:"varint,4,opt,name=instance_state,json=instanceState,proto3,enum=landscapehostagentapi.InstanceState" json:"instance_state,omitempty"` // instance_state are the defined states of the instances.
}

func (x *HostAgentInfo_InstanceInfo) Reset() {
	*x = HostAgentInfo_InstanceInfo{}
	mi := &file_hostagent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAgentInfo_InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAgentInfo_InstanceInfo) ProtoMessage() {}

func (x *HostAgentInfo_InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAgentInfo_InstanceInfo.ProtoReflect.Descriptor instead.
func (*HostAgentInfo_InstanceInfo) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{1, 0}
}

func (x *HostAgentInfo_InstanceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostAgentInfo_InstanceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostAgentInfo_InstanceInfo) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *HostAgentInfo_InstanceInfo) GetInstanceState() InstanceState {
	if x != nil {
		return x.InstanceState
	}
	return InstanceState_Stopped
}

type Command_AssignHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Command_AssignHost) Reset() {
	*x = Command_AssignHost{}
	mi := &file_hostagent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command_AssignHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_AssignHost) ProtoMessage() {}

func (x *Command_AssignHost) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_AssignHost.ProtoReflect.Descriptor instead.
func (*Command_AssignHost) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Command_AssignHost) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Command_Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_Start) Reset() {
	*x = Command_Start{}
	mi := &file_hostagent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Start) ProtoMessage() {}

func (x *Command_Start) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Start.ProtoReflect.Descriptor instead.
func (*Command_Start) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Command_Start) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Command_Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_Stop) Reset() {
	*x = Command_Stop{}
	mi := &file_hostagent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Stop) ProtoMessage() {}

func (x *Command_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Stop.ProtoReflect.Descriptor instead.
func (*Command_Stop) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Command_Stop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Command_Install struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cloudinit *string `protobuf:"bytes,2,opt,name=cloudinit,proto3,oneof" json:"cloudinit,omitempty"` // cloudinit is the yaml configuration to optionally pass to an instance.
	// URL to a WSL rootfs image we will download and import from. It will be registered under "id".
	// If this entry is not set, Ubuntu Pro for WSL will download a package from the Microsoft store
	// matching WSL distribution name as available in wsl --install.
	RootfsURL *string `protobuf:"bytes,3,opt,name=rootfsURL,proto3,oneof" json:"rootfsURL,omitempty"`
}

func (x *Command_Install) Reset() {
	*x = Command_Install{}
	mi := &file_hostagent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command_Install) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Install) ProtoMessage() {}

func (x *Command_Install) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Install.ProtoReflect.Descriptor instead.
func (*Command_Install) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Command_Install) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command_Install) GetCloudinit() string {
	if x != nil && x.Cloudinit != nil {
		return *x.Cloudinit
	}
	return ""
}

func (x *Command_Install) GetRootfsURL() string {
	if x != nil && x.RootfsURL != nil {
		return *x.RootfsURL
	}
	return ""
}

type Command_Uninstall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_Uninstall) Reset() {
	*x = Command_Uninstall{}
	mi := &file_hostagent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command_Uninstall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Uninstall) ProtoMessage() {}

func (x *Command_Uninstall) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Uninstall.ProtoReflect.Descriptor instead.
func (*Command_Uninstall) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Command_Uninstall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SetDefault changes the default instance on the host.
type Command_SetDefault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Command_SetDefault) Reset() {
	*x = Command_SetDefault{}
	mi := &file_hostagent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command_SetDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_SetDefault) ProtoMessage() {}

func (x *Command_SetDefault) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_SetDefault.ProtoReflect.Descriptor instead.
func (*Command_SetDefault) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{2, 5}
}

func (x *Command_SetDefault) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ShutdownHost forces a shut down of the agent/controller from landscape perspective (it may autorestart).
type Command_ShutdownHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Command_ShutdownHost) Reset() {
	*x = Command_ShutdownHost{}
	mi := &file_hostagent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command_ShutdownHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_ShutdownHost) ProtoMessage() {}

func (x *Command_ShutdownHost) ProtoReflect() protoreflect.Message {
	mi := &file_hostagent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_ShutdownHost.ProtoReflect.Descriptor instead.
func (*Command_ShutdownHost) Descriptor() ([]byte, []int) {
	return file_hostagent_proto_rawDescGZIP(), []int{2, 6}
}

var File_hostagent_proto protoreflect.FileDescriptor

var file_hostagent_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0xfa, 0x03, 0x0a, 0x0d, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4f, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6c, 0x61, 0x6e,
	0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61,
	0x70, 0x69, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x10, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x13, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x11, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x1a, 0x9e, 0x01, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6c,
	0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x22, 0xbf,
	0x06, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x4c, 0x0a, 0x0b, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63,
	0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x39, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65,
	0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x00, 0x52, 0x04, 0x73, 0x74, 0x6f,
	0x70, 0x12, 0x42, 0x0a, 0x07, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x48, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73,
	0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x48, 0x00, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12,
	0x4c, 0x0a, 0x0b, 0x73, 0x65, 0x74, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65,
	0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x48,
	0x00, 0x52, 0x0a, 0x73, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x52, 0x0a,
	0x0d, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65,
	0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x48, 0x6f, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x48, 0x6f, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x1a, 0x1e, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x1a, 0x17, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x16, 0x0a, 0x04, 0x53, 0x74, 0x6f,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x1a, 0x7b, 0x0a, 0x07, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x09,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x6e, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x21, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x55, 0x52, 0x4c, 0x88,
	0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x6e, 0x69, 0x74,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x55, 0x52, 0x4c, 0x1a, 0x1b,
	0x0a, 0x09, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x1c, 0x0a, 0x0a, 0x53,
	0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x0e, 0x0a, 0x0c, 0x53, 0x68, 0x75,
	0x74, 0x64, 0x6f, 0x77, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x63, 0x6d, 0x64,
	0x22, 0x8e, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x48, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73,
	0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2a, 0x29, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x2a, 0x39, 0x0a, 0x0c,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6e, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x02, 0x32, 0xc6, 0x01, 0x0a, 0x12, 0x4c, 0x61, 0x6e, 0x64,
	0x73, 0x63, 0x61, 0x70, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x55,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x24, 0x2e, 0x6c, 0x61, 0x6e, 0x64,
	0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70,
	0x69, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x1e, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x59, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x2e, 0x6c, 0x61, 0x6e,
	0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x1a, 0x1c, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x68, 0x6f, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x2f, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61,
	0x70, 0x65, 0x2d, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hostagent_proto_rawDescOnce sync.Once
	file_hostagent_proto_rawDescData = file_hostagent_proto_rawDesc
)

func file_hostagent_proto_rawDescGZIP() []byte {
	file_hostagent_proto_rawDescOnce.Do(func() {
		file_hostagent_proto_rawDescData = protoimpl.X.CompressGZIP(file_hostagent_proto_rawDescData)
	})
	return file_hostagent_proto_rawDescData
}

var file_hostagent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hostagent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_hostagent_proto_goTypes = []any{
	(InstanceState)(0),                 // 0: landscapehostagentapi.InstanceState
	(CommandState)(0),                  // 1: landscapehostagentapi.CommandState
	(*Empty)(nil),                      // 2: landscapehostagentapi.Empty
	(*HostAgentInfo)(nil),              // 3: landscapehostagentapi.HostAgentInfo
	(*Command)(nil),                    // 4: landscapehostagentapi.Command
	(*CommandStatus)(nil),              // 5: landscapehostagentapi.CommandStatus
	(*HostAgentInfo_InstanceInfo)(nil), // 6: landscapehostagentapi.HostAgentInfo.InstanceInfo
	(*Command_AssignHost)(nil),         // 7: landscapehostagentapi.Command.AssignHost
	(*Command_Start)(nil),              // 8: landscapehostagentapi.Command.Start
	(*Command_Stop)(nil),               // 9: landscapehostagentapi.Command.Stop
	(*Command_Install)(nil),            // 10: landscapehostagentapi.Command.Install
	(*Command_Uninstall)(nil),          // 11: landscapehostagentapi.Command.Uninstall
	(*Command_SetDefault)(nil),         // 12: landscapehostagentapi.Command.SetDefault
	(*Command_ShutdownHost)(nil),       // 13: landscapehostagentapi.Command.ShutdownHost
}
var file_hostagent_proto_depIdxs = []int32{
	6,  // 0: landscapehostagentapi.HostAgentInfo.instances:type_name -> landscapehostagentapi.HostAgentInfo.InstanceInfo
	7,  // 1: landscapehostagentapi.Command.assign_host:type_name -> landscapehostagentapi.Command.AssignHost
	8,  // 2: landscapehostagentapi.Command.start:type_name -> landscapehostagentapi.Command.Start
	9,  // 3: landscapehostagentapi.Command.stop:type_name -> landscapehostagentapi.Command.Stop
	10, // 4: landscapehostagentapi.Command.install:type_name -> landscapehostagentapi.Command.Install
	11, // 5: landscapehostagentapi.Command.uninstall:type_name -> landscapehostagentapi.Command.Uninstall
	12, // 6: landscapehostagentapi.Command.set_default:type_name -> landscapehostagentapi.Command.SetDefault
	13, // 7: landscapehostagentapi.Command.shutdown_host:type_name -> landscapehostagentapi.Command.ShutdownHost
	1,  // 8: landscapehostagentapi.CommandStatus.command_state:type_name -> landscapehostagentapi.CommandState
	0,  // 9: landscapehostagentapi.HostAgentInfo.InstanceInfo.instance_state:type_name -> landscapehostagentapi.InstanceState
	3,  // 10: landscapehostagentapi.LandscapeHostAgent.Connect:input_type -> landscapehostagentapi.HostAgentInfo
	5,  // 11: landscapehostagentapi.LandscapeHostAgent.SendCommandStatus:input_type -> landscapehostagentapi.CommandStatus
	4,  // 12: landscapehostagentapi.LandscapeHostAgent.Connect:output_type -> landscapehostagentapi.Command
	2,  // 13: landscapehostagentapi.LandscapeHostAgent.SendCommandStatus:output_type -> landscapehostagentapi.Empty
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_hostagent_proto_init() }
func file_hostagent_proto_init() {
	if File_hostagent_proto != nil {
		return
	}
	file_hostagent_proto_msgTypes[1].OneofWrappers = []any{}
	file_hostagent_proto_msgTypes[2].OneofWrappers = []any{
		(*Command_AssignHost_)(nil),
		(*Command_Start_)(nil),
		(*Command_Stop_)(nil),
		(*Command_Install_)(nil),
		(*Command_Uninstall_)(nil),
		(*Command_SetDefault_)(nil),
		(*Command_ShutdownHost_)(nil),
	}
	file_hostagent_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hostagent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostagent_proto_goTypes,
		DependencyIndexes: file_hostagent_proto_depIdxs,
		EnumInfos:         file_hostagent_proto_enumTypes,
		MessageInfos:      file_hostagent_proto_msgTypes,
	}.Build()
	File_hostagent_proto = out.File
	file_hostagent_proto_rawDesc = nil
	file_hostagent_proto_goTypes = nil
	file_hostagent_proto_depIdxs = nil
}
