# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hostagent_pb2 as hostagent__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hostagent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LandscapeHostAgentStub(object):
    """LandscapeHostAgent service.
    The connection is made from the hostagent (client) to the landscape server (sass or on-prem).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/landscapehostagentapi.LandscapeHostAgent/Connect',
                request_serializer=hostagent__pb2.HostAgentInfo.SerializeToString,
                response_deserializer=hostagent__pb2.Command.FromString,
                _registered_method=True)
        self.SendCommandStatus = channel.unary_unary(
                '/landscapehostagentapi.LandscapeHostAgent/SendCommandStatus',
                request_serializer=hostagent__pb2.CommandStatus.SerializeToString,
                response_deserializer=hostagent__pb2.Empty.FromString,
                _registered_method=True)


class LandscapeHostAgentServicer(object):
    """LandscapeHostAgent service.
    The connection is made from the hostagent (client) to the landscape server (sass or on-prem).
    """

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommandStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LandscapeHostAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=hostagent__pb2.HostAgentInfo.FromString,
                    response_serializer=hostagent__pb2.Command.SerializeToString,
            ),
            'SendCommandStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommandStatus,
                    request_deserializer=hostagent__pb2.CommandStatus.FromString,
                    response_serializer=hostagent__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'landscapehostagentapi.LandscapeHostAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('landscapehostagentapi.LandscapeHostAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LandscapeHostAgent(object):
    """LandscapeHostAgent service.
    The connection is made from the hostagent (client) to the landscape server (sass or on-prem).
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/landscapehostagentapi.LandscapeHostAgent/Connect',
            hostagent__pb2.HostAgentInfo.SerializeToString,
            hostagent__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommandStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/landscapehostagentapi.LandscapeHostAgent/SendCommandStatus',
            hostagent__pb2.CommandStatus.SerializeToString,
            hostagent__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
